import { z } from 'zod';

export const legacyUserItemSchema = z.object({
  id: z.union([z.number(), z.string()]).optional().nullable(),
  name: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  mobile: z.string().optional().nullable(),
  avatar: z.string().optional().nullable(),
  avatarUrl: z.string().optional().nullable(),
  avatar_url: z.string().optional().nullable(),
  google_id: z.string().optional().nullable(),
  googleId: z.string().optional().nullable(),
  is_verified: z.union([z.number(), z.boolean()]).optional().nullable(),
  role: z.union([z.number(), z.string()]).optional().nullable(),
  role_id: z.union([z.number(), z.string()]).optional().nullable(),
  roleId: z.union([z.number(), z.string()]).optional().nullable(),
  status: z.union([z.number(), z.string()]).optional().nullable(),
  college: z.string().optional().nullable(),
  course: z.string().optional().nullable(),
  gender: z.string().optional().nullable(),
  coupan: z.string().optional().nullable(),
  bio: z.string().optional().nullable(),
  telegramId: z.string().optional().nullable(),
  xp: z.number().optional().nullable(),
  current_streak: z.number().optional().nullable(),
  longest_streak: z.number().optional().nullable(),
  lastActivity: z.string().optional().nullable(),
  last_activity_date: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  metadata: z.record(z.string(), z.any()).optional().nullable(),
});

export const bulkUserMigrationSchema = z.object({
  entity: z.string().optional(),
  batch_index: z.number().optional(),
  chunk_size: z.number().optional(),
  batchSize: z.number().min(10).max(5000).default(2000),
  dryRun: z.boolean().default(false),
  data: z.array(legacyUserItemSchema).optional(),
  users: z.array(legacyUserItemSchema).optional(),
});

export type LegacyUserItem = z.infer<typeof legacyUserItemSchema>;
export type BulkUserMigrationInput = z.infer<typeof bulkUserMigrationSchema>;

// --- BATCH MIGRATION SCHEMAS ---
export const legacyBatchItemSchema = z.object({
  id: z.union([z.number(), z.string()]).optional().nullable(),
  name: z.string().optional().nullable(),
  topic: z.string().optional().nullable(),
  topicId: z.union([z.number(), z.string()]).optional().nullable(),
  description: z.string().optional().nullable(),
  slug: z.string().optional().nullable(),
  price: z.union([z.number(), z.string()]).optional().nullable(),
  payable: z.union([z.number(), z.string()]).optional().nullable(),
  renewalFee: z.union([z.number(), z.string()]).optional().nullable(),
  renewal_fee: z.union([z.number(), z.string()]).optional().nullable(),
  certificateFee: z.union([z.number(), z.string()]).optional().nullable(),
  certificate_fee: z.union([z.number(), z.string()]).optional().nullable(),
  offerId: z.string().optional().nullable(),
  limit: z.union([z.number(), z.string()]).optional().nullable(),
  img: z.string().optional().nullable(),
  image: z.string().optional().nullable(),
  association: z.string().optional().nullable(),
  logo: z.string().optional().nullable(),
  type: z.union([z.number(), z.string()]).optional().nullable(),
  startDate: z.string().optional().nullable(),
  start_date: z.string().optional().nullable(),
  endDate: z.string().optional().nullable(),
  end_date: z.string().optional().nullable(),
  schedule: z.string().optional().nullable(),
  about: z.string().optional().nullable(),
  learn: z.string().optional().nullable(),
  benefits: z.string().optional().nullable(),
  groupLink: z.string().optional().nullable(),
  groupLink1: z.string().optional().nullable(),
  groupLink2: z.string().optional().nullable(),
  telegramBroadcast: z.string().optional().nullable(),
  teacherId: z.union([z.number(), z.string()]).optional().nullable(),
  teacher_id: z.union([z.number(), z.string()]).optional().nullable(),
  TeacherPayment: z.union([z.number(), z.boolean()]).optional().nullable(),
  teacherPayment: z.union([z.number(), z.boolean()]).optional().nullable(),
  meetingLink: z.string().optional().nullable(),
  meeting_link: z.string().optional().nullable(),
  desc: z.string().optional().nullable(),
  nextClass: z.string().optional().nullable(),
  next_class: z.string().optional().nullable(),
  status: z.union([z.number(), z.string()]).optional().nullable(),
  accessTillDate: z.string().optional().nullable(),
  access_till_date: z.string().optional().nullable(),
  accessTillYear: z.union([z.number(), z.string()]).optional().nullable(),
  access_till_year: z.union([z.number(), z.string()]).optional().nullable(),
  field1: z.string().optional().nullable(),
  field2: z.string().optional().nullable(),
  field3: z.string().optional().nullable(),
  field4: z.string().optional().nullable(),
  field5: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  metadata: z.record(z.string(), z.any()).optional().nullable(),
});

export const bulkBatchMigrationSchema = z.object({
  entity: z.string().optional(),
  batch_index: z.number().optional(),
  chunk_size: z.number().optional(),
  batchSize: z.number().min(10).max(5000).default(2000),
  dryRun: z.boolean().default(false),
  data: z.array(legacyBatchItemSchema).optional(),
  batches: z.array(legacyBatchItemSchema).optional(),
});

export type LegacyBatchItem = z.infer<typeof legacyBatchItemSchema>;
export type BulkBatchMigrationInput = z.infer<typeof bulkBatchMigrationSchema>;

// --- ENROLLMENT MIGRATION SCHEMAS ---
export const legacyEnrollmentItemSchema = z.object({
  id: z.union([z.number(), z.string()]).optional().nullable(),
  user_id: z.union([z.number(), z.string()]).optional().nullable(),
  userId: z.union([z.number(), z.string()]).optional().nullable(),
  email: z.string().optional().nullable(),
  batch_id: z.union([z.number(), z.string()]).optional().nullable(),
  batchId: z.union([z.number(), z.string()]).optional().nullable(),
  slug: z.string().optional().nullable(),
  amount_payable: z.union([z.number(), z.string()]).optional().nullable(),
  amountPayable: z.union([z.number(), z.string()]).optional().nullable(),
  enrollment_type: z.union([z.number(), z.string()]).optional().nullable(),
  enrollmentType: z.union([z.number(), z.string()]).optional().nullable(),
  type: z.union([z.number(), z.string()]).optional().nullable(),
  status: z.union([z.number(), z.string()]).optional().nullable(),
  progress: z.union([z.number(), z.string()]).optional().nullable(),
  time_spent_seconds: z.union([z.number(), z.string()]).optional().nullable(),
  timeSpentSeconds: z.union([z.number(), z.string()]).optional().nullable(),
  amount_paid: z.union([z.number(), z.string()]).optional().nullable(),
  amountPaid: z.union([z.number(), z.string()]).optional().nullable(),
  certificate_fee: z.union([z.number(), z.string()]).optional().nullable(),
  certificateFee: z.union([z.number(), z.string()]).optional().nullable(),
  payment_status: z.string().optional().nullable(),
  paymentStatus: z.string().optional().nullable(),
  hasPaid: z.union([z.number(), z.boolean()]).optional().nullable(),
  has_paid: z.union([z.number(), z.boolean()]).optional().nullable(),
  payment_method: z.string().optional().nullable(),
  paymentMethod: z.string().optional().nullable(),
  coupon_code: z.string().optional().nullable(),
  couponCode: z.string().optional().nullable(),
  coupanCode: z.string().optional().nullable(),
  transaction_id: z.string().optional().nullable(),
  transactionId: z.string().optional().nullable(),
  invoice_id: z.string().optional().nullable(),
  invoiceId: z.string().optional().nullable(),
  subscription_id: z.string().optional().nullable(),
  subscriptionId: z.string().optional().nullable(),
  subscription_status: z.union([z.number(), z.string()]).optional().nullable(),
  subscriptionStatus: z.union([z.number(), z.string()]).optional().nullable(),
  subscription_active_on: z.string().optional().nullable(),
  subscriptionActiveOn: z.string().optional().nullable(),
  subscription_expires_on: z.string().optional().nullable(),
  subscriptionExpiresOn: z.string().optional().nullable(),
  paid_at: z.string().optional().nullable(),
  paidAt: z.string().optional().nullable(),
  certificate_id: z.string().optional().nullable(),
  certificateId: z.string().optional().nullable(),
  certificate_generated_at: z.string().optional().nullable(),
  certificateGeneratedAt: z.string().optional().nullable(),
  started_at: z.string().optional().nullable(),
  startedAt: z.string().optional().nullable(),
  startFrom: z.string().optional().nullable(),
  start_from: z.string().optional().nullable(),
  access_till: z.string().optional().nullable(),
  accessTill: z.string().optional().nullable(),
  override_access_days: z.union([z.number(), z.string()]).optional().nullable(),
  overrideAccessDays: z.union([z.number(), z.string()]).optional().nullable(),
  utm_source: z.string().optional().nullable(),
  utmSource: z.string().optional().nullable(),
  utm_medium: z.string().optional().nullable(),
  utmMedium: z.string().optional().nullable(),
  utm_campaign: z.string().optional().nullable(),
  utmCampaign: z.string().optional().nullable(),
  remark: z.string().optional().nullable(),
  sequential_learning: z.union([z.number(), z.boolean()]).optional().nullable(),
  sequentialLearning: z.union([z.number(), z.boolean()]).optional().nullable(),
  sequential_learning_with_assignments: z.union([z.number(), z.boolean()]).optional().nullable(),
  sequentialLearningWithAssignments: z.union([z.number(), z.boolean()]).optional().nullable(),
  created_at: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  metadata: z.record(z.string(), z.any()).optional().nullable(),
});

export const bulkEnrollmentMigrationSchema = z.object({
  entity: z.string().optional(),
  batch_index: z.number().optional(),
  chunk_size: z.number().optional(),
  batchSize: z.number().min(10).max(5000).default(2000),
  dryRun: z.boolean().default(false),
  data: z.array(legacyEnrollmentItemSchema).optional(),
  enrollments: z.array(legacyEnrollmentItemSchema).optional(),
});

export type LegacyEnrollmentItem = z.infer<typeof legacyEnrollmentItemSchema>;
export type BulkEnrollmentMigrationInput = z.infer<typeof bulkEnrollmentMigrationSchema>;

// --- PAYMENT MIGRATION SCHEMAS ---
export const legacyPaymentItemSchema = z.object({
  id: z.union([z.number(), z.string()]).optional().nullable(),
  enrollment_id: z.union([z.number(), z.string()]).optional().nullable(),
  enrollmentId: z.union([z.number(), z.string()]).optional().nullable(),
  course_enrollment_id: z.union([z.number(), z.string()]).optional().nullable(),
  amount: z.union([z.number(), z.string()]).optional().nullable(),
  paid_at: z.string().optional().nullable(),
  paidAt: z.string().optional().nullable(),
  payment_method: z.string().optional().nullable(),
  paymentMethod: z.string().optional().nullable(),
  transaction_id: z.string().optional().nullable(),
  transactionId: z.string().optional().nullable(),
  invoice_id: z.string().optional().nullable(),
  invoiceId: z.string().optional().nullable(),
  purpose: z.string().optional().nullable(),
  is_gst_applicable: z.union([z.number(), z.boolean()]).optional().nullable(),
  isGstApplicable: z.union([z.number(), z.boolean()]).optional().nullable(),
  remarks: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  metadata: z.record(z.string(), z.any()).optional().nullable(),
});

export const bulkPaymentMigrationSchema = z.object({
  entity: z.string().optional(),
  batch_index: z.number().optional(),
  chunk_size: z.number().optional(),
  batchSize: z.number().min(10).max(5000).default(2000),
  dryRun: z.boolean().default(false),
  data: z.array(legacyPaymentItemSchema).optional(),
  payments: z.array(legacyPaymentItemSchema).optional(),
});

export type LegacyPaymentItem = z.infer<typeof legacyPaymentItemSchema>;
export type BulkPaymentMigrationInput = z.infer<typeof bulkPaymentMigrationSchema>;
